---
- name: install nginx exporter
  ansible.builtin.import_tasks: install.yml

- name: create nginx exporter config
  ansible.builtin.import_tasks: config.yml

- name: Ensure nginx_exporter is started and enabled
  become: true
  ansible.builtin.systemd:
    name: nginx_exporter
    state: started
    enabled: true
    daemon_reload: true
